name: ESLint
on: 
  push:
    paths:
      - '**.js'
      - '.eslintrc.js'
      - '.github/workflows/eslint.yml'

jobs: 
  eslint:
    name: ESLintチェック
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn lint